# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Episode.create(title: "The Green Slime", air_date: "Pilot", genre: "Drama, Horror, Sci-Fi", synopsis: "Earth-orbiting inventor Joel Hodgson invites us to watch The Green Slime (1968) with him and his robot friends.", episode_number: 100)
Episode.create(title: "Invaders from the Deep", air_date: "Nov. 24, 1988", genre: "Sci-Fi", synopsis: "In between tending to some sick vacuum-flowers, Joel Hodgson and his robot buddy Crow begin their first movie-riffing experiment aboard the Satellite of Love.", episode_number: 101)
Episode.create(title: "Revenge of the Mysterons from Mars", air_date: "Nov. 24, 1988", genre: "Action, Family, Sci-Fi", synopsis: "Joel and his faithful robot companions celebrate Thanksgiving by scarfing down a chopped up Captain Scarlet serial repackaged as a TV film.", episode_number: 102)
Episode.create(title: "Star Force: Fugitive Alien II", air_date: "Nov. 27, 1988", genre: "Sci-Fi", synopsis: "Today's experiment features real humans from Japan and a budget that must've been tens of dollars.", episode_number: 103)
Episode.create(title: "Gamera vs. Barugon", air_date: "Dec. 4, 1988", genre: "Action, Fantasy, Sci-Fi", synopsis: "The historic first meeting between Gamera and the crew of the Satellite of Love.", episode_number: 104)
Episode.create(title: "Gamera", air_date: "Dec. 11, 1988", genre: "Sci-Fi", synopsis: "Crow is a frozen Christmas tree and Tom is busy, so Joel has to watch the original Gamera film all by himself.", episode_number: 105)
Episode.create(title: "Gamera vs. Gaos", air_date: "Dec. 18, 1988", genre: "Action, Adventure, Family", synopsis: "Crow is a frozen Christmas tree and Tom is busy, so Joel has to watch the original Gamera film all by himself.", episode_number: 106)
Episode.create(title: "Gamera vs. Zigra", air_date: "Dec. 31, 1988", genre: "Action, Adventure, Horror", synopsis: "Crow gets unfrozen just in time for yet another Gamera film, and we meet the Mads for the first time.", episode_number: 107)
Episode.create(title: "Gamera vs. Guiron", air_date: "Jan. 8, 1989", genre: "Action, Adventure, Family", synopsis: "As two Earth boys plead for Gamera to rescue them from a planet of cannibals, Crow experiences a wonderful dream in which he turn the tables on the Mads.", episode_number: 108)
Episode.create(title: "Phase IV", air_date: "Jan. 15, 1989", genre: "Horror, Sci-Fi, Thriller", synopsis: "This week's film is a deep sci-fi story about ants that leaves Crow wishing he'd brought a pair of boots into the theater.", episode_number: 109)
Episode.create(title: "Cosimc Princess", air_date: "Jan. 22, 1989", genre: "Adventure, Sci-Fi, Drama", synopsis: "The stranded crew of the Satellite of Love have no sympathy for the stranded crew of Moonbase Alpha when they take in two repackaged episodes of Space: 1999.", episode_number: 110)
Episode.create(title: "Humanoid Woman", air_date: "Jan. 29, 1989", genre: "Sci-Fi", synopsis: "A Russian film about a bug-eyed alien babe is the backdrop for a variety of antics aboard the Satellite of Love.", episode_number: 111)
Episode.create(title: "Fugitive Alien", air_date: "Feb. 5, 1989", genre: "Action, Sci-Fi", synopsis: "With Crow disassembled, Joel and Servo are left by themselves to tackle Part 1 of this baffling Japanese sci-fi epic.", episode_number: 112)
Episode.create(title: "SST: Death Flight", air_date: "Feb. 19, 1989", genre: "Adventure, Drama", synopsis: "Joel, Crow, and Servo sit through a star-studded TV movie about a doomed SST flight while Gypsy goes through some interesting changes.", episode_number: 113)
Episode.create(title: "Mighty Jack", air_date: "Mar. 5, 1989", genre: "Action, Sci-Fi", synopsis: 'The 007-ish exploits of Mighty Jack -- a government organization created to defeat the notorious crime syndicate known as "Q" -- took everything that was bad about espionage movies and threw the rest out.', episode_number: 114)
Episode.create(title: "Superdome", air_date: "Mar. 12, 1989", genre: "Crime, Drama, Sport", synopsis: "Servo writes a letter to his uncle in which he recalls many fond memories of his time aboard the satellite. Meanwhile, the crew are subjected to a TV drama about a New Orleans Super Bowl full of intrigue, romance, and catfish.", episode_number: 115)
Episode.create(title: "City on Fire", air_date: "Mar. 19, 1989", genre: "Action, Drama", synopsis: "This week's experiment is disastrous disaster film City on Fire (1979), which assures viewers the events depicted could happen in any city, anywhere. Even, as Tom points out, while we're watching this.", episode_number: 116)
Episode.create(title: "Time of the Apes", air_date: "Apr. 2, 1989", genre: "Action, Fantasy, Sci-Fi", synopsis: "Adapted (i.e., shredded and stitched into incoherence) from the 1974 Japanese series Saru No Gundan, Time Of The Apes follows the travails of a scientist and two small children who are accidentally frozen and thaw into a future ruled by apes.", episode_number: 117)
Episode.create(title: "The Million Eyes of Summuru", air_date: "May. 7, 1989", genre: "Action, Adventure", synopsis: "As groovy femme fatale Sumuru plots world domination, Joel gets even with the 'bots for locking him out of the ship.", episode_number: 118)
Episode.create(title: "Hanger 18", air_date: "May. 14, 1989", genre: "Action, Biography, Sci-Fi", synopsis: "The crew discover disturbing secrets in Crow's memory bank while watching a film about bland government officials investigating, and then trying to cover up, a flying saucer crash.", episode_number: 119)
Episode.create(title: "The Last Chase", air_date: "May. 21, 1989", genre: "Action, Adventure, Sci-Fi", synopsis: "This week's film features two intrepid heroes fleeing their Orwellian futuristic society in a souped-up racecar - but Joel and friends are more interested in reading fan mail from their adoring public.", episode_number: 120)
Episode.create(title: "The Legend of Dinosaurs", air_date: "May. 21, 1989", genre: "Sci-Fi", synopsis: "Joel and the Bots suffer through a dreary '70s dinosaur movie from Japan. Where's Doug McClure when you need him?", episode_number: 121)
